[package]
name = "fill-array"
version = "0.2.1"
edition = "2021"
description = "A rust macro allowing to fill arrays with an expression"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "~1.0"
syn = "~2.0"
proc-macro2 = "~1"

[dev-dependencies]
macrotest = "~1.0"